default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
development:
  <<: *default
  adapter: postgresql
  database: facebook_database
  username: postgres
  password: 123
  host: localhost
  port: 5432
  pool: 5
